name: build docs

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup project
        if: ${{ steps.setup.outputs.status }}
        uses: ./.github/workflows/setup.yml

      - name: deno-task test
        run: deno task test

      - name: deno-task build-npm
        run: deno task build-npm

      - name: deno-task build-npm-dist
        run: deno task build-npm-dist

      - name: create npm branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: npm
          FOLDER: npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
