name: build npm

on: workflow_dispatch

permissions:
  contents: write

jobs:
  setup-deno:
    runs-on: ubuntu-latest
    steps:
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

  setup-node:
    runs-on: ubuntu-latest
    steps:
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3

  test:
    needs: [setup-deno, clone-repo]
    runs-on: ubuntu-latest
    steps:
      - name: deno-task test
        run: deno task test

  build-npm:
    needs: [test, setup-node]
    runs-on: ubuntu-latest
    steps:
      - name: deno-task build-npm
        run: deno task build-npm

  create-npm-branch:
    needs: build-npm
    runs-on: ubuntu-latest
    steps:
      - name: create npm release branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: npm
          FOLDER: npm
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docs:
    needs: build-npm
    runs-on: ubuntu-latest
    steps:
      - name: deno-task build-docs
        run: deno task build-docs

  deploy-docs:
    needs: build-docs
    runs-on: ubuntu-latest
    steps:
      - name: deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
