name: build-docs

on: workflow_dispatch

permissions:
  contents: write

jobs:
  clone-repo:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
        with:
          ref: "main"
  
  setup-project:
    needs: clone-repo
    uses: ./.github/workflows/function-setup.yml

  build-docs-and-commit-github-pages:
    needs: setup-project
    uses: ./.github/workflows/function-build-docs.yml
