name: Generate TypeDoc

on: workflow_dispatch

permissions:
  contents: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - name: setup repo
        uses: actions/checkout@v3

      - name: install rsync
        run: apt-get update && apt-get install -y rsync

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: npm install
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: generate typedoc
        run: npm run build-docs "/kitchensink-ts/"

      - name: deploy github pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: docs
