name: Generate TypeDoc

on: workflow_dispatch

jobs:
  build-docs:
    runs-on: windows-latest
    steps:
      - name: setup node
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: npm install
      - uses: bahmutov/npm-install@v1.6.0
        with:
          useLockFile: false
      - name: generate typedoc
      - run: npm run build-docs "/kitchensink-ts/"
      - name: deploy github pages
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          build_dir: "/docs/"
