name: function-setup

on: workflow_call

permissions:
  contents: write

jobs:
  function-setup:
    runs-on: ubuntu-latest
    steps:
      - name: setup deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x
