name: publish-to-jsr

on:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write # The OIDC ID token is used for authentication with JSR.

jobs:
  publish-to-jsr:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v4
        with:
          ref: "main"

      - name: setup project
        uses: ./.github/actions/setup

      - name: publish to jsr.io
        shell: bash
        run: deno task publish-jsr
